### ISSUE TITLE
Preparations for RELEASE on F-Droid and Aptoide

### ISSUE THREAD

**Issue by SecUpwN** [CellularPrivacy/Android-IMSI-Catcher-Detector#156]
This Issue shall serve as the central TODO for the public release of `WIP-Release v0.1.24-alpha` to [F-Droid](https://f-droid.org) (fulfilling #3 by @PowerPress) and [Aptoide](http://www.aptoide.com/). _Both stores have already been created by myself_ and are ready to be published so that our project will gain much more momentum than ever before. Once all the points in this Issue have been solved, the links to both stores will be published on our `README` here on GitHub. It is now upon you, how fast we will reach this goal. Spread the word!

I have reviewed all open Issues and linked everything that we _have to_ solve until officially publishing AIMSICD to avoid as much trouble as possible. I would like to see all of our silent followers, forkers and watchers to contribute to achieve all points here: So please chime in with code, stop your silence and **TALK TO US** here. This is **YOUR** chance to polish up our App before releasing it into the wild!

@E3V3A, @tobykurien, @andr3jx, @He3556 and of course also to our beloved @xLaMbChOpSx: These are the things to achieve before launching the rocket - let's all work on these, please:

---
- Requirements from the [F-Droid Inclusion Policy](https://f-droid.org/wiki/page/Inclusion_Policy):
- [x] `All applications in the repository must be Free and Open Source software – for example, released under a GPL or Apache license. Every effort is made to verify that this is actually the case, both by visual inspection of the source, and by building the application from the published source.` -  done since our project is fully licensed under GPL v3+.
- [x] `For software to be FOSS, the software in its entirety must be so - including all libraries and dependencies used.` - @tobykurien, please grab a coffee and do a full review of our code.
- [x] `The source code for the application must be maintained in a publicly accessible Version Control System which we have support for (git, hg, svn, bzr), and the source code needs to be maintained in an up to date state.` - done since we are using the awesome @GitHub.
- [x] `The software should not download additional executable binary files (e.g. non-free addons, auto-updates, etc)` - @E3V3A, please re-check how this point conflicts with #118.
- [x] `The software should use its own unique Android package ID. Where the application is a fork of another (even one not included in the F-Droid repository) it must have a new ID, different from the original.` - another point I'd like @tobykurien to inspect. We currently lack the API key that @xLaMbChOpSx used to create the previous builds - another challenge?
- [x] `Although not ideal, "non-functional" assets (e.g. artwork) may be acceptable under less permissive licenses than functional code - an example would be artwork assets that are licensed only for use with that particular game. In any case though, they must be included under some kind of license, and not be copyright violations` - done since @SgtObst did an awesome job to create all artwork contained on our repository under GPL v3+.
- [x] `Trademarks must not be infringed, and any other legal requirements must be adhered to` - @He3556 please verify that we do not infringe any trademarks. Thank you.
- [x] `Releases should be clearly tagged (or otherwise marked)` - I will personally clean up our Releases-Page as per Issue #149. Can you re-check all taggings, @tobykurien? Not sure if all the alpha-builds we had until now have to be re-tagged somewhere or if it is good as it is?
- [x] Verify that all above points are passing the [F-Droid Inclusion How-To](https://f-droid.org/wiki/page/Inclusion_How-To).

---
- Aptoide seems to have no special requirements. Nevertheless, some points to think about:
- [x] Should we participate in the [Certified Publishers Program](https://www.aptoide.com/page/publishers) of Aptoide?
- [x] Are there any other channels where I should create official repositories for publishing our App?

---
- Issues to be solved before bumping to version `WIP-Release v0.1.24-alpha`:
- [x] Solve the last few Issues in Bug Report for `WIP-Release v.0.1.24-alpha` (Issue #105).
- [x] Solve the Bug report of the current `WIP-Internal v0.1.24-alpha-build-13` (Issue #153).
- ~~Make AT Command Injector finally usable (Issue #23) - @tobykurien, please review that again.~~
- [x] Re-check that our [SOURCES](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/master/SOURCES) are on the bleeding edge.
- ~~Build: Automatic version and app name update with Gradle (Issue #147).~~
- ~~Build: Automatic upload of Travis-CI build to GitHub (Issue #148).~~
- [x] Automatic Updates from GitHub Release Page (Issue #118).
- [x] OpenCellID API key not working (Issue #90).
- ~~Detection 1: Changing LAC (Issue #91).~~
- [x] Improvements to our Maps Viewer as suggested by @E3V3A in Issue #13.
- [x] Refreshing About-Menu with Buttons (Issue #132) - can you help us here, @tobykurien?
- [x] Find a solution to the missing signature key. @xLaMbChOpSx can you send it to me, please?

With this Issue we now have a clear Roadmap of when `WIP-Release v0.1.24-alpha` will be published. Please do **NOT** add any new Issues in new posts here, rather let me know in our internal chat and I will add them to the OP. I want this list to be stable and clean so that everyone can monitor progress using the features of nested task lists. Feel free to make us aware of any other important things here.
