### ISSUE TITLE
Cell tracking can be active in offline mode without any location service even installed

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#835]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [ ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [ ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [ ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

* `AIMSICD` version (see the `About` screen):
* Phone and ROM running *current* release:
* Link to logfile without identifyable data:

---

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.

---

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

---

#### Screenshots
>If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by agilob** [comment]
PLEASE DON'T EDIT MY DESCRIPTION I DIDN'T WRITE IT

**Comment by SecUpwN** [comment]
@agilob, no need to shout in bold letters. I am just trying to make your Ossues better readable. Please use SHORT bug titles and USE the `Issue Template` that we provide. Thank you.

**Comment by agilob** [comment]
I didn't use bold letter.

My title of this issue was more descriptive then what you edited and I saw no need to add description.

`Issue Template` that's too long sentences and too long template to read when reporting an issue, especially when users are exposed to markdown, which is not too readable. It's in not my interest to get a bug:
1. reported
2. fixed

and I think the template is only blocking me from reporting. I think I reported the issue from mobile Octodroid client, which doesn't support issue templates... so, no, I probably won't use them :) 
Please don't edit what users report (unless user reports logs with sensitive data -> #599, in such case, yes edit it and remove sensitive data!)

**Comment by SecUpwN** [comment]
>I didn't use bold letter.

Not sure what https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/835#issuecomment-206830140 is then?

>t's in not my interest to get a bug:
>1. reported
>2. fixed

If you report a bug, it *should* be in your interest to get it fixed as well.
Anyhow, I hope that @CellularPrivacy/celltower will have a look at this Issue as well.

**Comment by agilob** [comment]
>If you report a bug, it should be in your interest to get it fixed as well.

It is, a little, but I'm not a daily user of AIMSICD. I'm an observer here who tried to contribute to the project and provided you a lot of information a few times, but was completely ignored on both github and email, so occasionally I test if AIMSICD is able to detect any 'suspected' behaviour.
